### ISSUE TITLE
Could you explain how to open an article or pdf?

### ISSUE THREAD

**Issue by tuannguyen110** [dcalacci/hiboard#1]
Hi,
Could you explain how to open an article or pdf file with this project?
I've settup as your guidance with code:
`yarn install
expo start --web
`
And then open http://localhost:19006/ in my browse. How can I open the pdf file or an article and make highlight? Is there anyway to get a link of highlight to open in other notebook?
Thank you!

**Comment by dcalacci** [comment]
Hi! There is a short line in the Readme about how to actually get it up and running.

The project runs off of a user's Pinboard `unread` articles. To get it running, paste a Pinboard API key in the text input that gets rendered when the project starts. It should pull unread articles from the pinboard account. If one of them is a link to a PDF file, a PDF file will be rendered.

**Comment by dcalacci** [comment]
I added a little label to make it clearer what to do.

**Comment by dcalacci** [comment]
Closing this! This tool is sort of in limbo for now.
