### ISSUE TITLE
I can't get hiboard to work correctly on windows 10

### ISSUE THREAD

**Issue by lockcp** [dcalacci/hiboard#2]
## The error message is as follows：
> ReferenceError: SharedArrayBuffer is not defined
./node_modules/webidl-conversions/lib/index.js

**I hope you can tell me how to use hiboard correctly, thank you sincerely for your guidance!**

**I found a solution.**
**But since I'm a newbie, I don't know what is the right way to call.**
[Solutions](https://stackoverflow.com/questions/64650119/react-error-sharedarraybuffer-is-not-defined-in-firefox)
> You need to set two response headers for your document:
Cross-Origin-Opener-Policy: same-origin Cross-Origin-Embedder-Policy: require-corp
These are new security requirements for using SharedArrayBuffer.
You can check in code if cross origin isolation is enabled:
if (crossOriginIsolated) { // SharedArrayBuffer is available }

**Comment by dcalacci** [comment]
Hi! Very sorry but I can't reproduce this. Seems like the network requests from your machine need to have the cross-origin headers set properly. I'm not sure why that's a requirement for your windows machine but not my linux or mac testing machines, though
